// export const CONFIG = {
//   firebaseConfig: {
//     apiKey: process.env.REACT_APP_FIREBASE_API_KEY,
//     authDomain: process.env.REACT_APP_FIREBASE_AUTH_DOMAIN,
//     projectId: process.env.REACT_APP_FIREBASE_PROJECT_ID,
//     storageBucket: process.env.REACT_APP_FIREBASE_STORAGE_BUCKET,
//     messagingSenderId: process.env.REACT_APP_FIREBASE_MESSAGING_SENDER_ID,
//     appId: process.env.REACT_APP_FIREBASE_APP_ID,
//     measurementId: process.env.REACT_APP_FIREBASE_MEASUREMENT_ID,
//   },
// }
export const CONFIG = {
  firebaseConfig: {
    apiKey: 'AIzaSyDC9lq0kitpyWDaovIu2N3WuC4_kEyVhGM',
    authDomain: 'cms-ticket-sale-b3325.firebaseapp.com',
    projectId: 'cms-ticket-sale-b3325',
    storageBucket: 'cms-ticket-sale-b3325.appspot.com',
    messagingSenderId: '1031886756776',
    appId: '1:1031886756776:web:fbd422686e58988d619b9d',
    measurementId: 'G-K120H37GLX',
  },
}
